version: '3.8'

services:
  auth-service:
    build: .
    ports:
      - '4002:3001'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - RABBITMQ_URI=${RABBITMQ_URI}
